### ISSUE TITLE
500 when entering gene: FBgn0283437

### ISSUE THREAD

**Issue by CodingBash** [CodingBash/FlyCAGE#80]
Entering gene FBgn0283437 with default (100 gene result count and all stages selected) in the input page form

**Comment by CodingBash** [comment]
And CG14742

**Comment by CodingBash** [comment]
`Oct 02 15:08:13 fly-tran-web app/web.1: java.lang.NullPointerException: null 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at edu.ilstu.biology.flytranscriptionwebapp.processor.GenomicCorrelationAnalysis.retrieveMrnaCorrelationResults(GenomicCorrelationAnalysis.java:96) ~[classes/:0.0.1-SNAPSHOT] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at edu.ilstu.biology.flytranscriptionwebapp.controller.OutputController.processOutput(OutputController.java:50) ~[classes/:0.0.1-SNAPSHOT] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [webapp-runner.jar:na] 
Oct 02 15:08:13 fly-tran-web app/web.1: 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144-cedar14] 
Oct 02 15:08:13 fly-tran-web heroku/router: at=info method=GET path="/output" host=fly-tran-web.herokuapp.com request_id=31a3e36e
`
